# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    groups:
      dev-dependencies:
        applies-to: version-updates
        dependency-type: development

  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: monthly
