version: '3'

services:
  workspace:
    build:
      args:
        WORKSPACE: /workspaces/raindrop-sync-chrome
    volumes:
      - .:/workspaces/raindrop-sync-chrome
    environment:
      DISPLAY: novnc:0.0
    healthcheck:
      disable: true

  novnc:
    image: theasp/novnc:latest
    environment:
      DISPLAY_WIDTH: '${NOVNC_DISPLAY_WIDTH:-1600}'
      DISPLAY_HEIGHT: '${NOVNC_DISPLAY_HEIGHT:-968}'
      RUN_XTERM: 'no'
    ports:
      - ${NOVNC_HOST:-0.0.0.0}:${NOVNC_PORT:-8080}:8080
