version: '3'

services:
  workspace:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - ..:/workspace
    environment:
      DISPLAY: novnc:0.0
    healthcheck:
      disable: true
    cap_add:
      - SYS_ADMIN

  novnc:
    image: theasp/novnc:latest
    environment:
      DISPLAY_WIDTH: '${NOVNC_DISPLAY_WIDTH:-1600}'
      DISPLAY_HEIGHT: '${NOVNC_DISPLAY_HEIGHT:-968}'
      RUN_XTERM: 'no'
    ports:
      - ${NOVNC_HOST:-0.0.0.0}:${NOVNC_PORT:-8080}:8080
