version: '3'

services:
  workspace:
    build:
      context: .
    volumes:
      - ..:/workspaces/raindrop-sync-chrome
    environment:
      DISPLAY: ${DISPLAY:-novnc:0.0}
    healthcheck:
      disable: true
    cap_add:
      - SYS_ADMIN
    shm_size: 2gb

  novnc:
    image: theasp/novnc:latest
    environment:
      DISPLAY_WIDTH: '${NOVNC_DISPLAY_WIDTH:-1600}'
      DISPLAY_HEIGHT: '${NOVNC_DISPLAY_HEIGHT:-968}'
      RUN_XTERM: 'no'
    ports:
      - ${NOVNC_HOST:-127.0.0.1}:${NOVNC_PORT:-8080}:8080
