name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - '.devcontainer/**'
      - '.vscode/**'
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.devcontainer/**'
      - '.vscode/**'
      - '**.md'
  workflow_dispatch:

permissions: read-all

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare images
        uses: docker/bake-action@v4
        with:
          targets: workspace
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          load: true
          push: false

      - name: Run checks
        run: docker compose run --rm -u root workspace make ci

      - name: Upload unit test coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          files: coverage/unit/cobertura-coverage.xml
          flags: unit
          verbose: true

      - name: Upload e2e test coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          files: coverage/e2e/cobertura-coverage.xml
          flags: e2e,ui,chrome
          verbose: true
