name: Release

on:
  push:
    tags:
      - v*

permissions: read-all

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: chrome-web-store
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build extension
        run: yarn run build

      - name: Create an archive
        run: zip -r raindrop-sync-for-chrome.zip dist

      - name: Preserve build artifact
        uses: actions/upload-artifact@v4
        with:
          name: raindrop-sync-for-chrome
          path: ./raindrop-sync-for-chrome.zip
          retention-days: 14

      # Release will be created if the tag is in the format v*
      - name: Create release
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: |
            raindrop-sync-for-chrome.zip
          generate_release_notes: true

      - name: Publish to Chrome Web Store (Testers)
        uses: MobileFirstLLC/cws-publish@2.1.1
        with:
          action: testers
          extension_id: ${{ vars.CWS_EXTENSION_ID }}
          client_id: ${{ secrets.CWS_CLIENT_ID }}
          client_secret: ${{ secrets.CWS_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CWS_REFRESH_TOKEN }}
          zip_file: ./raindrop-sync-for-chrome.zip
